# Generated by Django 5.2.8 on 2025-11-09 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField(verbose_name="Вопрос")),
                ("response", models.TextField(blank=True, verbose_name="Ответ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Время обработки (сек)"
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Источники информации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультация",
                "verbose_name_plural": "Консультации",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Порядковый номер документа в списке источников",
                        verbose_name="Номер в чате",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultation.consultation",
                        verbose_name="Консультация",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                        verbose_name="Документ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ консультации",
                "verbose_name_plural": "Документы консультации",
                "ordering": ["order"],
                "unique_together": {("consultation", "document")},
            },
        ),
        migrations.AddField(
            model_name="consultation",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="consultations",
                through="consultation.ConsultationDocument",
                to="documents.document",
                verbose_name="Связанные документы",
            ),
        ),
    ]
