# Generated by Django 5.2.8 on 2025-11-09 03:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "questions_count",
                    models.IntegerField(default=10, verbose_name="Количество вопросов"),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=list, verbose_name="Вопросы и варианты ответов"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный тест",
                "verbose_name_plural": "Сгенерированные тесты",
                "ordering": ["-created_at"],
            },
        ),
    ]
