# Generated by Django 5.2.8 on 2025-11-09 00:49

import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название документа"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=documents.models.document_upload_path,
                        verbose_name="Файл документа",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("rtf", "RTF"), ("docx", "DOCX")],
                        max_length=10,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байт)"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "Обрабатывается"),
                            ("processed", "Обработан"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "pages_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество страниц"
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-upload_date"],
            },
        ),
    ]
