# Generated by Django 5.2.8 on 2025-11-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("rtf", "RTF"),
                    ("docx", "DOCX"),
                    ("txt", "TXT"),
                ],
                max_length=10,
                verbose_name="Тип файла",
            ),
        ),
    ]
